SELECT  
    A.AUTHOR_ID, 
    B.AUTHOR_NAME, 
    A.CATEGORY, 
    SUM(C.SALES * A.PRICE) as TOTAL_SALES
FROM BOOK A
JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(C.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 
    A.AUTHOR_ID,
    A.CATEGORY,
    B.AUTHOR_NAME
ORDER BY 
    A.AUTHOR_ID,
    A.CATEGORY DESC