-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR,
        ABS(SIZE_OF_COLONY - B.MAX_SIZE) as YEAR_DEV,
        ID
FROM ECOLI_DATA A
LEFT JOIN (
    Select YEAR(A.DIFFERENTIATION_DATE) as YEAR,
            MAX(SIZE_OF_COLONY) as MAX_SIZE
    from ECOLI_DATA A
    GROUP BY YEAR(A.DIFFERENTIATION_DATE) 
    ) B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC
